import "./globals.css";
import React from "react";
import StyledComponentsRegistry from "../lib/registry";
import { ContextProvider } from "./context";
import { AppHeader } from "../components/common/Heading/AppHeader";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <main>
          <ContextProvider>
            <StyledComponentsRegistry>
              <div
                style={{
                  height: "100vh",
                  width: "100%",
                  display: "flex",
                  flexDirection: "column",
                }}
              >
                <AppHeader />
                {children}
              </div>
            </StyledComponentsRegistry>
          </ContextProvider>
        </main>
      </body>
    </html>
  );
}
