import "./globals.css";
import { List } from "../components/common/List/List";
import { ListItem } from "../components/common/ListItem/LIstItem";
import { Sidebar } from "../components/common/SideBar/Sidebar";
import React from "react";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <main>
          <div className="h-screen flex bg-gray-200">
            <Sidebar>
              <div className="pt-3 pb-1 pl-2.5 w-52">
                <p className="font-bold text-2xl">Event Vet</p>
              </div>
              <List>
                <ListItem text={"Procedure"} />
                <ListItem text={"Invoice"} />
              </List>
            </Sidebar>
            {children}
          </div>
        </main>
      </body>
    </html>
  );
}
